name: openapi-maven-ci
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build:
    uses: belgif/workflows/.github/workflows/openapi-ci-workflow.yml@main
